name: Track and sync tracked files
on:
  push:
    branches:
      - main
      - master

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
  GH_TOKEN: ${{ secrets.TEMPLATES_GITHUB_TOKEN }}

jobs:
  sync-diffs-with-template-builder:
    name: "Track updated files"
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'chadwcarlson' && github.event.commits[0].author.name != 'GitHub Action' }}
    steps:
      - name: 'get repo'
        uses: actions/checkout@v3
        with:
          token: ${{secrets.TEMPLATES_GITHUB_TOKEN }}
      - name: 'test vars'
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF_NAME
          echo $GITHUB_REF
          echo $GITHUB_REPOSITORY
          curl https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA.diff > latest.diff
          cat latest.diff