name: Track and sync tracked files
on:
  push:
    branches:
      - main
      - master

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
  GH_TOKEN: ${{ secrets.TEMPLATES_GITHUB_TOKEN }}

jobs:
  sync-diffs-with-template-builder:
    name: "Track updated files"
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'chadwcarlson' && github.event.commits[0].author.name != 'GitHub Action' }}
    steps:
      - name: 'get repo'
        uses: actions/checkout@v3
        with:
          token: ${{secrets.TEMPLATES_GITHUB_TOKEN }}
      - name: 'get diff'
        run: |
          curl https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA.diff > latest.diff
      - name: 'track changes'
        id: changes-made
        run: |
          TRACKED_FILES=( .platform.app.yaml .platform/services.yaml .platform/applications.yaml )
          MODIFIED_FILES=()
          OPEN_TB_PR=0

          # DETECT CHANGES
          for FILE in "${TRACKED_FILES[@]}"
          do
              if test -f "$FILE"; then
                  echo "Checking $FILE"
                  CHANGE=$(grep 'diff --git a/$FILE b/$FILE' latest.diff)
                  if [ "$CHANGE" == "" ];then
                      echo "$FILE is unchanged"
                  else 
                      echo "$FILE has been modified"
                      OPEN_TB_PR=1
                      MODIFIED_FILES+=($FILE)
                  fi 
              else
                  echo "File $FILE not found"
              fi
          done
          echo "modified_files=$MODIFIED_FILES" >> $GITHUB_ENV
          echo "sync_tb=$OPEN_TB_PR" >> $GITHUB_ENV
      - name: 'apply changes'
        run: | 
          # APPLY CHANGES
          if [ "$${{ env.sync_tb }}" -eq 1 ]; then
              echo "One of the tracked files has been changed."
              echo "${{ env.modified_files }}"
          else
              echo "No revisisions detected. All is well.";
          fi